#!/usr/bin/perl
#
# Simple routine that will relay a challenge via a Jabber server.  You should
# consider using an SSL only jabber server! 
#
# Champ Clark III (cclark@quadrantsec.com)
#
# Based on:
# Copyright (c) 2005, Thus0 <thus0@free.fr>. All rights reserved.
# released under the terms of the GNU General Public License v2

use strict;
use Net::XMPP;

## Configuration

my $username = "JabberSendChallenge";
my $password = "MyPassword";

my $to = "$ARGV[0]";
my $id = "$ARGV[1]";

my $body = <STDIN>;

my $send = $id . " : " . $body;

my $resource = "PerlBot";

## End of configuration

#------------------------------------

# Google Talk & Jabber parameters :

my $hostname = 'jabber.example.com';
my $port = 5222;
my $componentname = 'jabber.example.com';
my $connectiontype = 'tcpip';
my $tls = 1;

#------------------------------------

my $Connection = new Net::XMPP::Client();

# Connect to Jabber server
my $status = $Connection->Connect(
       hostname => $hostname, port => $port,
       componentname => $componentname,
       connectiontype => $connectiontype, tls => $tls);

if (!(defined($status))) {
   print "ERROR:  XMPP connection failed.\n";
   print "        ($!)\n";
   exit(0);
}

# Change hostname
my $sid = $Connection->{SESSION}->{id};
$Connection->{STREAM}->{SIDS}->{$sid}->{hostname} = $componentname;

# Authenticate
my @result = $Connection->AuthSend(
       username => $username, password => $password,
       resource => $resource);

if ($result[0] ne "ok") {
   print "ERROR: Authorization failed: $result[0] - $result[1]\n";
   exit(0);
}

# Send message
$Connection->MessageSend(
       to => "$to\@$componentname", body => $send,
       resource => $resource);

